name: JMeter Performance Tests

on:
  push:
    branches:
      - main # Trigger on push to main branch (or any branch you prefer)
  pull_request:
    branches:
      - main # Trigger on PR targeting main branch

jobs:
  jmeter-test:
    runs-on: ubuntu-latest # Specify your runner (ubuntu-latest is common)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Checks out your code to the runner

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "11" # Set the Java version according to your JMeter requirements
          distribution: "temurin"

      - name: Install JMeter 5.6.3 from Apache Distribution
        run: |
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xvzf apache-jmeter-5.6.3.tgz
          sudo mv apache-jmeter-5.6.3 /opt/jmeter
          echo "JMeter installed at /opt/jmeter"

      - name: Install JMeter Plugins Manager
        run: |
          wget https://jmeter-plugins.org/get/ -O /opt/jmeter/lib/ext/jmeter-plugins-manager.jar

      - name: Install JMeter Plugins CLI runner & Stepping Thread Group
        run: |
          wget https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.3/cmdrunner-2.3.jar -P /opt/jmeter/lib/
          java -cp /opt/jmeter/lib/ext/jmeter-plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller
          /opt/jmeter/bin/./PluginsManagerCMD.sh install jpgc-casutg

      - name: Add JMeter to PATH, Verify Installation, And Run JMeter Tests
        run: |
          export JMETER_HOME=/opt/jmeter
          export PATH=$PATH:$JMETER_HOME/bin
          echo $PATH
          jmeter.sh -v
          jmeter -n -t tests/test_plan.jmx -l results/result.jtl -e -o reports/

      - name: Check JMeter Installation Directory
        run: |
          ls /opt/jmeter/bin

      - name: List result files
        run: ls -R /home/runner/work/boon-cypress-practice-one/boon-cypress-practice-one/results/.jtls

      - name: List JTL files
        run: find /home/runner/work/boon-cypress-practice-one/boon-cypress-practice-one/results/ -name '*.jtl'

      - name: List report files
        run: ls -R /home/runner/work/boon-cypress-practice-one/boon-cypress-practice-one/reports/.html

      - name: List HTML files
        run: find /home/runner/work/boon-cypress-practice-one/boon-cypress-practice-one/reports/ -name '*.html'

      - name: Upload JMeter Results as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          include-hidden-files: true
          path: results/

      - name: Send JMeter Results to Datadog via API
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${{ secrets.DATADOG_API_KEY }}" \
            -d @results/result.jtl \
            "https://api.datadoghq.com/api/v1/logs"
